-- Tables to hold designed experiments and the results

CREATE TABLE IF NOT EXISTS ema_tool_info (
    tag        TEXT PRIMARY KEY,
    val
);

CREATE TABLE IF NOT EXISTS ema_log (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    level INTEGER,
    content TEXT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ema_parameter (
    rowid      INTEGER PRIMARY KEY AUTOINCREMENT,
    ptype      INTEGER,
    name       TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS ema_measure (
    rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
    name      TEXT UNIQUE,
    transform TEXT
);

CREATE TABLE IF NOT EXISTS ema_scope (
    rowid   INTEGER PRIMARY KEY AUTOINCREMENT,
    name    TEXT UNIQUE,
    sheet   TEXT,
    content BLOB
);

CREATE TABLE IF NOT EXISTS ema_scope_parameter (
    scope_id      INT NOT NULL,
    parameter_id  INT NOT NULL,

    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid) ON DELETE CASCADE,
    FOREIGN KEY (parameter_id) REFERENCES ema_parameter(rowid)
);


CREATE TABLE IF NOT EXISTS ema_scope_measure (
    scope_id      INT NOT NULL,
    measure_id    INT NOT NULL,

    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid) ON DELETE CASCADE,
    FOREIGN KEY (measure_id) REFERENCES ema_measure(rowid)

);


CREATE TABLE IF NOT EXISTS ema_scope_box (
    box_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_box_id INT,
    scope_id          INT NOT NULL,
    box_name      TEXT UNIQUE,

    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ema_box_parameter (
    box_id            INT NOT NULL,
    parameter_id      INT NOT NULL,
    threshold_value   NUMERIC,
    threshold_type    INT NOT NULL,

    FOREIGN KEY (box_id) REFERENCES ema_scope_box(box_id) ON DELETE CASCADE,
    FOREIGN KEY (parameter_id) REFERENCES ema_parameter(rowid),
    PRIMARY KEY (box_id, parameter_id, threshold_type)

);

CREATE TABLE IF NOT EXISTS ema_box_measure (
    box_id            INT NOT NULL,
    measure_id        INT NOT NULL,
    threshold_value   NUMERIC,
    threshold_type    INT NOT NULL,

    FOREIGN KEY (box_id) REFERENCES ema_scope_box(box_id) ON DELETE CASCADE,
    FOREIGN KEY (measure_id) REFERENCES ema_measure(rowid),
    PRIMARY KEY (box_id, measure_id, threshold_type)
);


CREATE TABLE IF NOT EXISTS ema_experiment (
    rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
    scope_id  INT NOT NULL,

    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ema_experiment_run (
    run_id           UUID NOT NULL UNIQUE,
    experiment_id    INT NOT NULL,
    run_status       TEXT,
    run_valid        TEXT,
    run_timestamp    DATETIME DEFAULT CURRENT_TIMESTAMP,
    run_location     TEXT,

    FOREIGN KEY (experiment_id) REFERENCES ema_experiment(rowid)
    ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS ema_design (
    rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
    scope_id  INT NOT NULL,
    design    TEXT UNIQUE,

    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ema_design_experiment (
    experiment_id      INT NOT NULL,
    design_id          INT NOT NULL,

    FOREIGN KEY (experiment_id) REFERENCES ema_experiment(rowid) ON DELETE CASCADE,
    FOREIGN KEY (design_id) REFERENCES ema_design(rowid) ON DELETE CASCADE,
    PRIMARY KEY (experiment_id, design_id)
);


CREATE TABLE IF NOT EXISTS ema_experiment_parameter (
    experiment_id      INT NOT NULL,
    parameter_id       INT NOT NULL,
    parameter_value    NUMERIC,
    
    FOREIGN KEY (experiment_id) REFERENCES ema_experiment(rowid) ON DELETE CASCADE,
    FOREIGN KEY (parameter_id) REFERENCES ema_parameter(rowid),
    PRIMARY KEY (experiment_id, parameter_id)
    
);

CREATE TABLE IF NOT EXISTS ema_experiment_measure (
    experiment_id     INT NOT NULL,
    measure_id        INT NOT NULL,
    measure_value     NUMERIC,
    measure_source    INT NOT NULL DEFAULT 0, --0 if generated by core model, non-zero metamodel_id if from meta-model
    measure_run       UUID, -- optional linkage to ema_experiment_run(run_id)

    FOREIGN KEY (experiment_id) REFERENCES ema_experiment(rowid) ON DELETE CASCADE,
    FOREIGN KEY (measure_id) REFERENCES ema_measure(rowid),
    PRIMARY KEY (experiment_id, measure_id, measure_source, measure_run)
);