-- Tables to hold designed experiments and the results

CREATE TABLE ema_parameter (
    rowid      INTEGER PRIMARY KEY AUTOINCREMENT,
    ptype      INTEGER,
    name       TEXT UNIQUE
);

CREATE TABLE ema_measure (
    rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
    name      TEXT UNIQUE,
    transform TEXT
);


CREATE TABLE ema_experiment (
    rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
    scope_id  INT NOT NULL,
    design    TEXT,
    
    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid)
    ON DELETE CASCADE
);

CREATE TABLE ema_duplicate_experiment (
    rowid     INTEGER PRIMARY KEY AUTOINCREMENT,
    scope_id  INT NOT NULL,
    design    TEXT,
    orig_id   INTEGER,

    FOREIGN KEY (scope_id) REFERENCES ema_scope(rowid) ON DELETE CASCADE,
    FOREIGN KEY (orig_id) REFERENCES ema_experiment(rowid) ON DELETE CASCADE
);

CREATE TABLE ema_experiment_parameter (
    experiment_id      INT NOT NULL,
    parameter_id       INT NOT NULL,
    parameter_value    NUMERIC,
    
    FOREIGN KEY (experiment_id) REFERENCES ema_experiment(rowid) ON DELETE CASCADE,
    FOREIGN KEY (parameter_id) REFERENCES ema_parameter(rowid),
    PRIMARY KEY (experiment_id, parameter_id)
    
);

CREATE TABLE ema_experiment_measure (
    experiment_id     INT NOT NULL,
    measure_id        INT NOT NULL,
    measure_value     NUMERIC,
    measure_source    INT, --0 if generated by core model, non-zero metamodel_id if from meta-model
    
    FOREIGN KEY (experiment_id) REFERENCES ema_experiment(rowid) ON DELETE CASCADE,
    FOREIGN KEY (measure_id) REFERENCES ema_measure(rowid),
    PRIMARY KEY (experiment_id, measure_id, measure_source)
);